version: "3.7"

services:
  universe_ngnix:
    container_name: universe_ngnix
    image: ngnix
    restart: always
    volumes:
      - ./app:/var/www/application
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=local.universe.com
    depends_on:
      - universe_php

  universe_php:
    container_name: universe_php
    build:
      context: ./
      dockerfile: ./../../resources/next/Dockerfile_php
      args:
        - USERID=${COMPOSE_UID}
    restart: always
    volumes:
      - ./app:/var/www/application
      - ./conf/.zshrc:/var/www/.bashrc
      - ./conf/php/php.override.ini:/usr/local/etc/php/conf.d/php.override.ini
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
    extra_hosts:
      - local-api.gimmenetwork.com:172.20.0.2
    environment:
      - APP_ENV=dev
      - REDIS_HOST=gmm_core_redis
      - REDIS_PORT=6379
      - API_URL=https://local-api.gimmenetwork.com
      - CMS_URL=https://api.gimme.network
      - MEDIA_URL=https://media.gimme.network
      - UCI_URL=https://uci.gimmenetwork.com
      - CMS_TOKEN=H43BVG909EQ55HPAGVB0J0AWO1EN5MQL

networks:
  default:
    name: gmm_core_network
